### ISSUE TITLE
Fix Expense page aesthetic details

### ISSUE THREAD

**Issue by alberto-m-santos** [Fabio-Morais/Money-Clinic#60]
![image](https://user-images.githubusercontent.com/89933736/156740908-59958a44-558d-4ae3-84cc-5c5c226883f4.png)

**Comment by Fabio-Morais** [comment]
![image](https://user-images.githubusercontent.com/35969631/156751668-774582a4-cbc6-4551-be39-dd521b7b38d0.png)
